package com.livebattle.game;

import android.app.Activity;import android.content.*;import android.graphics.*;import android.media.MediaPlayer;import android.net.Uri;import android.os.*;import android.view.*;import java.io.*;import java.net.*;import java.util.*;import org.json.*;
public class GameActivity extends Activity{
 private BattleView view;private MediaPlayer player;private ArrayList<String> music=new ArrayList<>();private int track=-1;private final Handler h=new Handler(Looper.getMainLooper());private String endpoint="";private boolean running=true;private int taps=0;private long lastTap=0;
 private final Runnable poller=()->{if(!running)return;if(!endpoint.isEmpty())pollEvents();h.postDelayed(()->{if(running){if(!endpoint.isEmpty())pollEvents();h.postDelayed(poller,1200);}},1200);};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);immersive();endpoint=getIntent().getStringExtra("endpoint");if(endpoint==null)endpoint="";ArrayList<String>x=getIntent().getStringArrayListExtra("music");if(x!=null)music=x;view=new BattleView(this);setContentView(view);startMusic();h.postDelayed(poller,100);}
 private void immersive(){getWindow().getDecorView().setSystemUiVisibility(5894|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);}
 private void startMusic(){if(!music.isEmpty())playTrack(0);}private void playTrack(int i){try{if(music.isEmpty())return;track=(i+music.size())%music.size();if(player!=null)player.release();player=new MediaPlayer();player.setDataSource(this,Uri.parse(music.get(track)));player.setOnCompletionListener(mp->playTrack(track+1));player.setVolume(.75f,.75f);player.setOnPreparedListener(MediaPlayer::start);player.prepareAsync();}catch(Exception ignored){}}
 private void pollEvents(){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(900);c.setReadTimeout(900);if(c.getResponseCode()!=200)return;Scanner s=new Scanner(c.getInputStream()).useDelimiter("\\A");String body=s.hasNext()?s.next():"[]";JSONArray a=new JSONArray(body);for(int i=0;i<a.length();i++){JSONObject e=a.getJSONObject(i);h.post(()->view.applyEvent(e));}c.disconnect();}catch(Exception ignored){}}).start();}
 @Override public void onBackPressed(){exit();}private void exit(){running=false;h.removeCallbacksAndMessages(null);if(player!=null){player.release();player=null;}finish();}
 private class BattleView extends View{Paint p=new Paint(3);Bitmap bg;ArrayList<Player>A=new ArrayList<>(),B=new ArrayList<>();BattleView(Context c){super(c);loadBg(getIntent().getStringExtra("bg"));setLayerType(View.LAYER_TYPE_SOFTWARE,null);}void loadBg(String s){try{if(s!=null){InputStream in=getContentResolver().openInputStream(Uri.parse(s));bg=BitmapFactory.decodeStream(in);in.close();}}catch(Exception ignored){}}
  protected void onDraw(Canvas c){int w=getWidth(),hh=getHeight();if(bg!=null)c.drawBitmap(bg,null,new Rect(0,0,w,hh),p);else{p.setShader(new LinearGradient(0,0,w,hh,Color.rgb(20,45,75),Color.rgb(85,25,35),Shader.TileMode.CLAMP));c.drawRect(0,0,w,hh,p);p.setShader(null);}p.setColor(0x33000000);c.drawRect(0,0,w/2,hh,p);c.drawRect(w/2,0,w,hh,p);p.setColor(Color.WHITE);c.drawRect(w/2-2,0,w/2+2,hh,p);p.setTextSize(62);p.setTypeface(Typeface.DEFAULT_BOLD);p.setShadowLayer(8,0,3,Color.BLACK);c.drawText("A",18,72,p);c.drawText("B",w-65,72,p);p.clearShadowLayer();drawPlayers(c,A,0,w/2);drawPlayers(c,B,w/2,w);p.setTextSize(14);p.setTypeface(Typeface.DEFAULT);p.setColor(0xCCFFFFFF);c.drawText("LIVE BATTLE",w/2-45,hh-22,p);}
  void drawPlayers(Canvas c,ArrayList<Player> list,int l,int r){int size=58,gap=5,cols=Math.max(1,(r-l-12)/(size+gap));for(int i=0;i<list.size();i++){int row=i/cols,col=i%cols;float x=l+8+col*(size+gap),y=92+row*(size+gap);p.setColor(Color.WHITE);c.drawCircle(x+size/2,y+size/2,size/2+2,p);if(list.get(i).bmp!=null)c.drawBitmap(list.get(i).bmp,null,new RectF(x,y,x+size,y+size),p);else{p.setColor(Color.DKGRAY);c.drawCircle(x+size/2,y+size/2,size/2,p);}p.setColor(Color.WHITE);p.setTextSize(9);String n=list.get(i).name;if(n.length()>8)n=n.substring(0,8);c.drawText(n,x,y+size+11,p);}}
  void applyEvent(JSONObject e){try{String type=e.optString("type");if("comment".equals(type)){String t=e.optString("text").trim().toUpperCase(Locale.ROOT);if(t.startsWith("A"))add(A,e.optString("user","Viewer"),e.optString("avatarUrl",""));else if(t.startsWith("B"))add(B,e.optString("user","Viewer"),e.optString("avatarUrl",""));}invalidate();}catch(Exception ignored){}}
  void add(ArrayList<Player> side,String n,String u){Player q=new Player(n,u);side.add(q);if(A.size()+B.size()>120){if(A.size()>B.size())A.remove(0);else B.remove(0);}if(!u.isEmpty())new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();InputStream in=c.getInputStream();q.bmp=BitmapFactory.decodeStream(in);in.close();h.post(this::invalidate);}catch(Exception ignored){}}).start();}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_UP){long n=System.currentTimeMillis();taps=(n-lastTap<600)?taps+1:1;lastTap=n;if(taps>=5){taps=0;exit();}}return true;}}
 private static class Player{String name,url;Bitmap bmp;Player(String n,String u){name=n;url=u;}}
}
